/**
 * @file    http_server.c
 * @brief   HTTP server module implementation
 *
 * Uses the ESP-IDF esp_http_server component.
 * The static page (index.html) is embedded into the firmware via CMakeLists
 * EMBED_FILES and read directly from flash at runtime — no filesystem required.
 *
 * Sensor data is read by the DHT11 driver; the relay control stub functions
 * will be replaced once the GPIO driver is complete.
 */

#include <string.h>
#include "esp_err.h"
#include "esp_log.h"
#include "esp_http_server.h"
#include "http_server.h"
#include "dht11.h"
#include "light_ctrl.h"

static const char *TAG = "http_server";

/* ----------------------------------------------------------------
 * Embedded static resources (generated by the CMakeLists EMBED_FILES directive)
 * Symbol naming rule: ESP-IDF uses only the filename part (no directory),
 * replacing non-alphanumeric characters with _
 * web/index.html -> index.html -> _binary_index_html_start
 * ---------------------------------------------------------------- */
extern const uint8_t index_html_start[] asm("_binary_index_html_start");
extern const uint8_t index_html_end[]   asm("_binary_index_html_end");

/* Server handle, used to release resources on stop */
static httpd_handle_t s_server = NULL;


/* ================================================================
 *  Sensor data cache — updated by dht11_read, read directly by HTTP handlers.
 *  Avoids triggering a DHT11 read on every HTTP request
 *  (DHT11 sampling period >= 2 s).
 * ================================================================ */

/* Cache the most recently successful temperature and humidity reading */
static dht11_data_t s_sensor_cache = {
    .temperature = 0.0f,
    .humidity    = 0.0f,
};

/* Cache obstacle detection state: 1 = detected (door closed), 0 = no obstacle (door open) */
static int s_obstacle_cache = 0;

/* Cache IR sensor state: 1 = motion detected, 0 = no motion */
static int s_ir_cache = 0;

/* Cache light sensor: percent 0-100, raw ADC value, digital state 1=bright/0=dark */
static int s_light_percent = 0;
static int s_light_raw     = 0;
static int s_light_digital = 0;

/**
 * @brief  Update the sensor cache; should be called periodically from main_task
 *         (recommended interval >= 2 s).
 *
 * On read failure the previous valid data is retained — the cache is not cleared.
 */
void http_server_update_sensor(void)
{
    dht11_data_t data;
    esp_err_t ret = dht11_read(&data);
    if (ret == ESP_OK) {
        s_sensor_cache = data; /* update cache */
    } /* on read failure retain the last cache; no log printed (DHT11 module pending replacement) */
}

void http_server_update_obstacle(int detected)
{
    s_obstacle_cache = detected;
}

void http_server_update_ir(int detected)
{
    s_ir_cache = detected;
}

void http_server_update_light(int percent, int raw, int digital)
{
    s_light_percent = percent;
    s_light_raw     = raw;
    s_light_digital = digital;
}

/* ================================================================
 *  Relay control — drives GPIO15 via the relay module
 * ================================================================ */


/* ================================================================
 *  URI handlers
 * ================================================================ */

/**
 * @brief  GET / — return the embedded index.html
 *
 * @param req  HTTP request handle
 * @return ESP_OK
 */
static esp_err_t handler_get_index(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    httpd_resp_send(req,
                    (const char *)index_html_start,
                    index_html_end - index_html_start);
    return ESP_OK;
}

/**
 * @brief  GET /api/sensors — return sensor data as JSON
 *
 * Response format:
 *   {"temperature": 25.0, "humidity": 60.0}
 *
 * @param req  HTTP request handle
 * @return ESP_OK
 */
static esp_err_t handler_get_sensors(httpd_req_t *req)
{
    char buf[160];

    /* Read directly from the cache; do not block in the HTTP handler waiting for sensor sampling */
    /* door: 1 = closed (sensor detects door), 0 = open (no obstruction) */
    /* motion: 1 = motion detected, 0 = no motion                        */
    snprintf(buf, sizeof(buf),
             "{\"temperature\":%.1f,\"humidity\":%.1f,\"door\":%d,\"motion\":%d,"
             "\"light\":%d,\"lux\":%d,\"lux_raw\":%d,\"bright\":%d}",
             s_sensor_cache.temperature,
             s_sensor_cache.humidity,
             s_obstacle_cache,
             s_ir_cache,
             light_ctrl_get_state(),
             s_light_percent,
             s_light_raw,
             s_light_digital);

    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, buf);
    return ESP_OK;
}

/**
 * @brief  POST /api/relay — parse JSON and set relay state
 *
 * Request body format:
 *   {"id": 1, "state": 1}   (state: 1=on, 0=off)
 *
 * Response format:
 *   {"id": 1, "state": 1}   (reflects the actual state after execution)
 *
 * @param req  HTTP request handle
 * @return ESP_OK / ESP_FAIL
 */
static esp_err_t handler_post_relay(httpd_req_t *req)
{
    char buf[64] = {0};

    /* Read request body, at most 63 bytes to prevent overflow */
    int len = httpd_req_recv(req, buf, sizeof(buf) - 1);
    if (len <= 0) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Empty body");
        return ESP_FAIL;
    }

    /* Simple parsing of the id and state fields from the JSON body.
     * TODO: if more fields are added, switch to cJSON for safer parsing */
    int relay_id = 0, state = 0;
    if (sscanf(buf, "{\"id\":%d,\"state\":%d}", &relay_id, &state) != 2) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Invalid JSON");
        return ESP_FAIL;
    }

    /* Validate relay ID (only 1 channel is currently supported) */
    if (relay_id != 1) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Invalid relay id");
        return ESP_FAIL;
    }

    light_ctrl_set_manual(state);
    int actual_state = light_ctrl_get_state();

    /* Return the actual state */
    char resp[32];
    snprintf(resp, sizeof(resp), "{\"id\":%d,\"state\":%d}", relay_id, actual_state);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, resp);
    return ESP_OK;
}


/* ================================================================
 *  URI table
 * ================================================================ */

static const httpd_uri_t uri_index = {
    .uri      = "/",
    .method   = HTTP_GET,
    .handler  = handler_get_index,
};

static const httpd_uri_t uri_sensors = {
    .uri      = "/api/sensors",
    .method   = HTTP_GET,
    .handler  = handler_get_sensors,
};

static const httpd_uri_t uri_relay = {
    .uri      = "/api/relay",
    .method   = HTTP_POST,
    .handler  = handler_post_relay,
};


/* ================================================================
 *  Public interface implementation
 * ================================================================ */

/**
 * @brief  Start the HTTP server and register all routes
 *
 * @return ESP_OK on success, ESP_FAIL on failure
 */
esp_err_t http_server_start(void)
{
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.lru_purge_enable = true; /* auto-evict the oldest connection when the limit is reached */

    ESP_LOGI(TAG, "starting http server on port %d", config.server_port);

    if (httpd_start(&s_server, &config) != ESP_OK) {
        ESP_LOGE(TAG, "failed to start http server");
        return ESP_FAIL;
    }

    httpd_register_uri_handler(s_server, &uri_index);
    httpd_register_uri_handler(s_server, &uri_sensors);
    httpd_register_uri_handler(s_server, &uri_relay);

    ESP_LOGI(TAG, "http server started");
    return ESP_OK;
}

/**
 * @brief  Stop the HTTP server and release resources
 */
void http_server_stop(void)
{
    if (s_server) {
        httpd_stop(s_server);
        s_server = NULL;
        ESP_LOGI(TAG, "http server stopped");
    }
}
